<?php
	$db=new Database();
	$moddetail=$_GET['mod'];
	$arbiling = new Arbilling();
	$core=new Core();
	
	$user=$_SESSION['uname'];
	$data = $arbiling->showDetail($user);
	extract($data);
?>
<style type="text/css">
    table { page-break-inside:auto }
    tr    { page-break-inside:avoid; page-break-after:auto }
    thead { display:table-header-group }
    tfoot { display:table-footer-group }
</style>

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv="Content-type" content="text/html;charset=UTF-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link rel=File-List
href="FIF%20RADANA%20MCF%20MEGA%20FINANCE_files/filelist.xml">
<!--[if !mso]>
<style>
v\:* {behavior:url(#default#VML);}
o\:* {behavior:url(#default#VML);}
x\:* {behavior:url(#default#VML);}
.shape {behavior:url(#default#VML);}
</style>
<![endif]-->
<style id="FIF RADANA MCF MEGA FINANCE_9033_Styles">
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
.xl159033
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl639033
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:"_\(* \#\,\#\#0\.00_\)\;_\(* \\\(\#\,\#\#0\.00\\\)\;_\(* \0022-\0022??_\)\;_\(\@_\)";
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl649033
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl659033
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:16.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"_\(* \#\,\#\#0\.00_\)\;_\(* \\\(\#\,\#\#0\.00\\\)\;_\(* \0022-\0022??_\)\;_\(\@_\)";
	text-align:left;
	vertical-align:top;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl669033
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl679033
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:underline;
	text-underline-style:single;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl689033
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl699033
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl709033
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:top;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl719033
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:top;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
-->
</style>
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="FIF RADANA MCF MEGA FINANCE_9033" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=633 style='border-collapse:
 collapse;table-layout:fixed;width:475pt'>
 <col width=31 style='mso-width-source:userset;mso-width-alt:1133;width:23pt'>
 <col width=91 style='mso-width-source:userset;mso-width-alt:3328;width:68pt'>
 <col width=64 style='width:48pt'>
 <col width=81 style='mso-width-source:userset;mso-width-alt:2962;width:61pt'>
 <col width=64 span=2 style='width:48pt'>
 <col width=81 style='mso-width-source:userset;mso-width-alt:2962;width:61pt'>
 <col width=64 style='width:48pt'>
 <col width=93 style='mso-width-source:userset;mso-width-alt:3401;width:70pt'>
 <tr height=27 style='height:20.25pt'>
  <td height=27 width=31 style='height:20.25pt;width:23pt' align=left
  valign=top><!--[if gte vml 1]><v:shapetype id="_x0000_t75" coordsize="21600,21600"
   o:spt="75" o:preferrelative="t" path="m@4@5l@4@11@9@11@9@5xe" filled="f"
   stroked="f">
   <v:stroke joinstyle="miter"/>
   <v:formulas>
    <v:f eqn="if lineDrawn pixelLineWidth 0"/>
    <v:f eqn="sum @0 1 0"/>
    <v:f eqn="sum 0 0 @1"/>
    <v:f eqn="prod @2 1 2"/>
    <v:f eqn="prod @3 21600 pixelWidth"/>
    <v:f eqn="prod @3 21600 pixelHeight"/>
    <v:f eqn="sum @0 0 1"/>
    <v:f eqn="prod @6 1 2"/>
    <v:f eqn="prod @7 21600 pixelWidth"/>
    <v:f eqn="sum @8 21600 0"/>
    <v:f eqn="prod @7 21600 pixelHeight"/>
    <v:f eqn="sum @10 21600 0"/>
   </v:formulas>
   <v:path o:extrusionok="f" gradientshapeok="t" o:connecttype="rect"/>
   <o:lock v:ext="edit" aspectratio="t"/>
  </v:shapetype><v:shape id="Picture_x0020_1" o:spid="_x0000_s1097" type="#_x0000_t75"
   style='position:absolute;margin-left:9pt;margin-top:4.5pt;width:82.5pt;
   height:49.5pt;z-index:1;visibility:visible' o:gfxdata="UEsDBBQABgAIAAAAIQBamK3CDAEAABgCAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbJSRwU7DMAyG
70i8Q5QralM4IITW7kDhCBMaDxAlbhvROFGcle3tSdZNgokh7Rjb3+8vyWK5tSObIJBxWPPbsuIM
UDltsK/5x/qleOCMokQtR4dQ8x0QXzbXV4v1zgOxRCPVfIjRPwpBagArqXQeMHU6F6yM6Rh64aX6
lD2Iu6q6F8phBIxFzBm8WbTQyc0Y2fM2lWcTjz1nT/NcXlVzYzOf6+JPIsBIJ4j0fjRKxnQ3MaE+
8SoOTmUi9zM0GE83SfzMhtz57fRzwYF7S48ZjAa2kiG+SpvMhQ4kvFFxEyBNlf/nZFFLhes6o6Bs
A61m8ih2boF2XxhgujS9Tdg7TMd0sf/X5hsAAP//AwBQSwMEFAAGAAgAAAAhAAjDGKTUAAAAkwEA
AAsAAABfcmVscy8ucmVsc6SQwWrDMAyG74O+g9F9cdrDGKNOb4NeSwu7GltJzGLLSG7avv1M2WAZ
ve2oX+j7xL/dXeOkZmQJlAysmxYUJkc+pMHA6fj+/ApKik3eTpTQwA0Fdt3qaXvAyZZ6JGPIoiol
iYGxlPymtbgRo5WGMqa66YmjLXXkQWfrPu2AetO2L5p/M6BbMNXeG+C934A63nI1/2HH4JiE+tI4
ipr6PrhHVO3pkg44V4rlAYsBz3IPGeemPgf6sXf9T28OrpwZP6phof7Oq/nHrhdVdl8AAAD//wMA
UEsDBBQABgAIAAAAIQAmyu4xEQIAAD0FAAASAAAAZHJzL3BpY3R1cmV4bWwueG1spFRNj9sgFLxX
6n9A3Lu2kzgfVuxVtNFWlVZt1A/1TPBzjIrBAjbJ/vs+wE6UqoequWEGZob35nn9eO4kOYKxQquS
Zg8pJaC4roU6lPTH9+cPS0qsY6pmUiso6RtY+li9f7c+16ZgirfaEKRQtsCNkrbO9UWSWN5Cx+yD
7kEh2mjTMYef5pDUhp2QvJPJJE3nie0NsNq2AG4bEVoFbnfSTyDlJkpALdzGlhQ9+N3hTGN0F09z
Lat0nXhTfhkYcPGlaaosm03TK+a3Amz0abzil+Oex/NFlg83EAo3AvVVz+mLRpX9XXc5n2X5/ILd
6E7j9p+6k2W+yC/QVXdU6wWPsuq4E3xnBg+fjztDRF3SCSWKddglRN2rAZLR5Hom3mAFsrxo/ssO
fWP/0bWOCYVa+qll6gAb2wN3mB6vFnuAlqJc+Lyxu5eifxZSEqPdT+Haby3r0XKGPWWFB+/2FfP4
T2nUTSM4bDV/7UC5GEkDkjkcB9uK3lJiCuj2gNU1n+rwQlZYw7/ii+82ihaX6WqBM7fH5q2yVe4r
iPzOgOPtvfxjN8aKxyjY3geHFefGdPcqeB4sITlj/8KYUfJW0jA+8SVwdoR7NJ3l2TSjhCM+nyzn
eRrCEm14mt5Y9xH03ZaIJ8JmYX9CotjxxTpfiavEENJYiBBQHIlhTqTAHGyZY2Pxbv5Dw83436t+
AwAA//8DAFBLAwQUAAYACAAAACEAqiYOvrwAAAAhAQAAHQAAAGRycy9fcmVscy9waWN0dXJleG1s
LnhtbC5yZWxzhI9BasMwEEX3hdxBzD6WnUUoxbI3oeBtSA4wSGNZxBoJSS317SPIJoFAl/M//z2m
H//8Kn4pZRdYQde0IIh1MI6tguvle/8JIhdkg2tgUrBRhnHYffRnWrHUUV5czKJSOCtYSolfUma9
kMfchEhcmzkkj6WeycqI+oaW5KFtjzI9M2B4YYrJKEiT6UBctljN/7PDPDtNp6B/PHF5o5DOV3cF
YrJUFHgyDh9h10S2IIdevjw23AEAAP//AwBQSwMEFAAGAAgAAAAhAHVomVASAQAAggEAAA8AAABk
cnMvZG93bnJldi54bWxMUE1PhDAUvJv4H5pn4sW4BVaEIGVDNCbGwyYLxr02UD4ibUlbAf31dmE3
eGrmTWfezIt3E+/QwJRupSDgbhxATBSybEVN4CN/vQ8BaUNFSTspGIEfpmGXXF/FNCrlKA5syEyN
rInQESXQGNNHGOuiYZzqjeyZsFwlFafGQlXjUtHRmvMOe47ziDlthd3Q0J49N6z4yr45gaPu0s/+
PRyzIXCD4e4lP9I2J+T2ZkqfABk2mfXzWf1WEvDgVMXWgMTmm7pUFI1UqDow3f7a8Mu8UpIjJUcC
tmwhu/m1eF9VmhkCfuD6C3OZuO7D1nEAn1yNXLTbs9bu/Kf1Qj/wZ+ainWV4TZPEFqynS/4AAAD/
/wMAUEsDBAoAAAAAAAAAIQBI/rbhMRgAADEYAAAUAAAAZHJzL21lZGlhL2ltYWdlMS5wbmeJUE5H
DQoaCgAAAA1JSERSAAACuwAAAHEIBgAAANWPa3kAAAABc1JHQgJAwH3FAAAACXBIWXMAAA7EAAAO
xAGVKw4bAAAAGXRFWHRTb2Z0d2FyZQBNaWNyb3NvZnQgT2ZmaWNlf+01cQAAF7FJREFUeNrtnTGu
H7cRh32BtBGUIEkVIEWsRnFrBbIOYMVxqSIP6QIYEAzDcCWrCHKBXCBFUhvICXyBIHWKwDfwERw9
Re+9/e9bkkNyhjPkfgZ+hZ/2z+UMh+S3Qy73vdevX7+HEEIIIYTQisIJgfSfX/7sh73wC0IIIYRQ
ENgF1PQgNyX8hRBCCCE0CHYBtDEPB/gUIYQQQqiOr7pgVwq2AFrZf71+x5++7Ygf1vA7bYm0xvSI
sdRTJ+YctEJfHBb4dBQ9P3gPPjXbLiT1qy2r9d619baoj+VKiNdKi1csePjdy86RbeAZSzP4pjVO
LX0wi21Rxkq0NuB2w25vkJ09SLVt9/InsGsLuxr9C9gFdoFdX99EgsIotnn2XXQuyG2CXe2gOluQ
jpocIgeaRTneoLu/zwzA6/103VNWlAlzdAZvZDlRYimqb0bEmdcDXfTsMbCLeh6G3WDqLIE6emKI
FnjWk5H0+giwaw2IkQEF2LWFMY+Hp1keqEeUoXk/D9jVThpY9CGAF8jtiXd3iFo1WD0nhdmyuxYT
Q+k6TWjuhb0zZON6y5H6X3pNzXUrwK5nZnXm8aWnf2qtWFmNVVZjVq9fR40xaE3ArYZdrwGNbO5c
fhyxfKYNu70DqDbsWmdEI2xlsILdXoiNsGXAuw9Z1mv28aU3plvqPmqssn7o0xq7gV0gdxnYXQl6
ves/G+yOGDA1t0O0ZB5bB/AZs3EjYVfLl7PDrtf+7xlg1zMD2QLbI8eq0bYBu2gU5B7FQzjonDV4
I9Xbc09db+bBEna1B9BosCttixVgV9uXre2k4WPvPmRRpzONL72T+GxjVattlrALKAK4pXgImZ2c
DXqj1XMW2NWYTKUTiBWkaUwgKwHKCNi1mAy1YbcnOza6D/XWaWQ8RRhfLCZ1a9iVjlWWtgG7yBpy
c7EwRYYyajBHrZ/nCyQtGVdL2B31soQ27Gq1+0qwaz0Z1patZbN3H5oNdkf5xsLWXJmjMqIetllk
qAFdALcmFsJnKaNCZfSOFh12taDBeiku4oBf0w6jJ4gR9nhlfqx87N2Heu2MCLsavrGw03KPt3cf
sR772KsL5PY8cE8DcWfdEzsr7LZkMc4Gu5bLiF6TBLDb/1b76D40I+xa+8bKTo3suPfvtWyL0B5o
bsCtiYHDCs7iwDMD98ywqzmRzgS7Fi8SSWIT2LX/8uNo2LWE0db6rDS+ALv+sGs1VqL1s7hLwK4X
dM7WwSLAbu2AtTLsWg7co7PIZ4RdSx9796FaG6LArqVvgF0/2AVyAVyLdp8W6DyW0WYNwKiwqzEI
rwK7mlsYPAHlLLCr6WPvPrQq7PbU29LGVWFXy8cAL5Br0c5TZy+tYXT2jhUBdmsGwLPDbmtbjVre
BnZtfOzdh2rhMRLsWvkG2I0NuwDvupBrxX5LwJ1lp10hICPCrtYgPBvstmSkosH12WDX2sfefUhz
AltlfAF2/WFXe6xEawHuKWFXM8u7UkeKArvaGZoZYdfqnsDuOWDXsg/NDrsWvgF2/WB3dJ2RD+Rq
3v90sKs1Sa4WpNFgV3MQBnbbX96xiI/VYdfCx959KGosefoG2AV2AdzYgHt62G3J0K7aeSLBrqQ+
Z4Nd7Uyc5VPxWWF3hI+9+1DUWPL0jaWNUWF3tG0jx0rkB7nW95aWf4rMpqTDrRy4kWBXexBfFXZn
BZQzwq7Ez5H7kKad1vE0yjfA7jywC/CeD3CB3crM7eodJRrsWgzis8PuCEDphTFg19bH3n2opQ4R
YXfUg6hFHxndx2aEXbK7sSE36j1PBbtn7STA7tywqw1IwO6YOswGuxH3fq4Ku1FAdaRtI2AX4PWB
XK/MMbDbkeUFdoFdz3JGARKwG68Os8Kupq9ngl3NlYJosDvStlFjJVoLcFvb+9SZXWAX2I1Ujifs
asUJsFvvh9Vg1/LhadbxRTM2o415rbaNGiuB3HUAt6etTwG7Z+0MwO78sHv022iTnHXWKQJQWPoh
UvYyUixFHl+84nLEWDXqAXPEWAngrgO4ve27PBSeuRMAu+vDrudkaQUHEdoS2AV2pZP5iD5h5XNL
4AF214Tc0YCr1a7LgmHrJAvsAruRYTfaZKk1gUaCgdF18OpDEZfCo40vvcAbdd9vBNuAXQDXGnCX
h12PTM4ZYVc7QDUH3AjZQM0lIU1/jxhgPAe8CJOo1KZRfWg07GrEkqdvrCd7LztG2Dcqbs4MvNbt
tALcLg27Fk8swO4Yv9WWN7pDW2ZINAaXEZmcSIOxdltG3MdmYb9mDHg8sFj7Jlpcj/L3aNusx0oA
Nz7gjvbfMrCby5rUZHJX6jhW9fcGFY/ObV2OdzbFKt69s7mjYddrMhg9EVm2Z7QHIS1fj+pLHkA1
si2iwlRUyI0CuN5+XAJ2JZNYCXKtl9BWy+wi5L0agFB0CKG/Ig/IjQC40fx5KtjVeIIHdhFCCCEE
4NpvgQN2K2FXe4kU2EUIIYSQF+R6A+4I24HdhLMkf9dsFGAXIYQQQqsD7mi7Nf09LRxJXiwb9XIW
sIsQQgghC8g9C9wCuwLHbf/dqx7ALkIIIYRmBFxvuLXkqangqHRUWIQgBnYRQgghtDrgznSSwzRw
lHOEd72jZnmBXYQQQgjAjQy3I9hpCjiSHggfLcjPAru/+MmDHxBCCCEvzQS6I2EyOtyO4pTwsFsT
INHqDOwihBBC68NuFMCdBW5HJwanAd2ZYPemTmcBbwZahBBCwO54wJ0Nbr3aJ3x2dP/1M2AX2EUI
IYSiwK7klKgI4HgGqJ0KdiUfiUhBcBSHA7sIIYTQOWHXG3TPDLZTwK70ZbSaoAJ2fWC39F9u4Kr5
T1pOabCsubanjr02tdbDws+19de4rsVPvfXUalvN+1nGUC1oaLd/bZvV/jcyRlr9qHWN5liZ+vfR
Pjgj7EaA2xmgdgrYbWnY3G89GwnY7YM6C9jVBGNr2NUAOUmZlr+V1tUTdrX9MrIdNONIG5Zb2rVn
3OiFXU041urLrddojbmasNvTV2eA3dyqshVUArYLwK4G6HrbBez6ZhxXgF2LemjVJfXvLVBhDbsS
WPRuW0vYlfgpCuyO8F/rby2yydqw21Ofmmsss9yrwK4UeL3323r5BNgt1KE2ewvsxoDdnkmvdQ9X
7YBrMTFpZGYsJ0gLGyLBbmsMWvtF435acdQDJpawq2WTlQ+9xhQptGuAcgvsjtq6Eg12teFudqiN
li0OA7stR4xFPpYM2PWBsBVg12Kv8Uiok9yvZtK2gt2IftGE3d79nT11sWxXK7s1Vwa8YbflHpIY
GPmQMiPs9gDvDFsSZt4aMUVmV7osEAF2z/jJ4Iiwm5p8gV19qGuBIg/Y1QbJ2WBXWqeZYLclg6m1
xQnYtdtr3OK7SPtDS3wS/aSEFfcAh4TdmjPrchvD93ZZN0DEDd4rwG5L5ik3cPZMkNp7/TT2TvaU
V/OfRkZwNOz21tOybXvvpwF0R/8eHXZ7Hio076fdj2v7Yy1418Jy7j6jYVdiVyTYHQ28UbZKRH7R
bQrYlWROS2fwajWGtHGB3Riwqz1BagNRq30jgLX3tz2wq5kF7annKH9awW4NlGlmJK3bNRrsavRj
D9gtlSFpV23YbW2jaLCrCbze2w9WOMlhqhfUWo8m0zypQdq4wK4f7ErLjAy7GnuTNaGu5/e5CS03
mWqBWAv0WsOuxu8iw26qLaXguArs9my/OhPsto7Z0WF3xIoyULsY7LZs9K4BaG14BHb99uxqAMfo
fZ1asGs54Wvs5/WE3dZtBVZA7b1nt+chRxt2V9rGoDV2ae8fboFd6ZYMTdhtjcWZYLd3TgZoF39B
rRV0gd3zwG5LViQC7FqX1wMFvSAZFXZHtoXF70bBbi8MarerVlyPgF2LONCE3dZVNo9VvFlhtwd4
AVpgtwp0gV1gVzJ4RoJdLejRBvxe2MhN0tqZM6k/e+FhFtjV3sLSulqh2a5WDwI9mVCrvmztP8tx
ROuhK2dbdNgqveNDthbYrf7YhHQbQ88XTIDdftjVBM/cSw5W97QAm5ZJcrSfNWHXEop6JukVYLe3
3Xtht+VBoscmiweilocxy76suZJTGxPWsNv7UDIDcHkA7xnBdsk9u7kTGCQBlLuudzsFsNv+tN7y
294Jrud+Nfb1TCrWE2SLDS2/84LdUfb1wK51/GlnUa1gt8Wu3rFAu62j9uVeYLXoZ70P2LNAVwuL
ALUngt2apyLpb1uCq8YWYLd9wrKEXemyqxfsamXVNG3umeA8Ybe3nivArgXERoBdrUx5lAcG760p
Nfce7UPJtTOBVy/wAq+Lw24KaluPJKvJGrccUXZ22EXnUAuMUE8Urb1Wio8zxvps8BX9076rQfV0
sNvzuxrQ7fUJsIsQQggBu7UwqgmsAO/JYLfma2zALrCLEEII2AV414DeU8Cu9PPCwC6wixBCCNgF
eNcC3uVht7R1QXrKA7AL7CKEEAJ2zwy8s0LvErArDZaje5ROd+ixBdhFCCGEgF2AF9hVq0Mt6JYC
qNeWs8AuQgghhM4FvDOxxVKwq1G2Vh2AXYQQQgihgLC74pPCaNDl6QshhBBCKBDsrgxmHqAL7CKE
EEIIBYLdldV6Bi9CCCGEEAJ2p4Fdi7N0EUIIIYQQsBsSeFniP4f++PTBP94eTfP0D3+/+dvXV7/9
+O3fHj757rNXr34qLevLL7/80aePfvxt7vibx5+8/CqyPz7/5NdfXdS50gez6NWrFz999vDBd/fa
aBMH6Lh/VPn5s+cfPH745N83MSTpWxf96OC63jq12/Hg++v7Pr36+uN7Y8WRHr7//aefvfqg6Nuc
nOIxZe9eR+3ZOn4iBOwOBl5AF9i1gt3IwHsPdBcF3qSdiwP+aNhtBaF9P9r3Fw/Y3YIpsAvsImAX
IWD3YILe/tvPHz3/9vr/I/lhm+m8qfvR32bXBZzsQOICgsnwmsBu00Pj7vejYXcPtDn4a61fNECU
wu4MtkRTzcvirS+X976YrnWvmrpofb+gtRyCEwG7CrB7AVO5pdl3ugHiLXDuJ53UpJoqqxZ2t2Vt
y0jV6chv22ufXb18kYMYSd1ry0tCVAJE3t5/929Se2vqNsyHb2zpgY/WGDvMWgrrcrhCsrl/Dia3
kCbJrtY8BEpgt9XXud9Z9IlSjBzB7hb67/2NzK4K9Fpc2wOFrfdtLasXfHt+T1AiYFcBdnOZ3dRy
5s11R3VMwVKprNZsWgv8pWAhVS9J3WvKS4JQJQC1wG6NHSN8qAm7knbSgt3ffPL8r29t37RZCnZz
Wwpqs5P7B9THH334TSnTmXswbYVdiz4hiZE97NbEK7CrD2atWVbt8qTl9trcAq2pTDKwi9Brnz27
28niCMD2GeC7a+5PKBeTnqCsLNTts2IJUGgFtUMYumdjvu7S8vJAYQ+7pbqZ+nATz6WXvWr7R02M
aezZvX5ovC3/XR1KD3+HYN5g+42t1z7/4uXzpyXYvalnyzalw3Y36BPSGNnD7k1Z+4d4YDcO7NZC
Xg3stlyvbTOwi9AssFvYw3d/Cfb/9z/KGKcmn1JZVT5J1L0V1ErXSureUl4Jdg8zgg33tPKL9Nqi
fYrbGCQxpgW72//fgtdxn720vTXbenvPd+WV9rCWtjC1Zna1+4Q0Rrb3e/bRk7+l6gbszgu7kt/k
TqmSXD8KdmvrCewiYPe17jaGi4zTQXlZQN5cv80aff711a/2S7s1ZbVkNLf3sgA1ad17YLfq+Kip
YbcMna39oybGtGB3v5Lx6dMH/5T22daXLG/L22e0E7DbukUmV3+LPiGNkdQqD5ldO9jteZGr9UWv
FniV1MMDdnvBn6BES4PtiD27R0uHR6B1M1FllyrfTKa//92TPx8tl0rLqsksHU3ipqAm9UMD7Epe
UOu55+yZXUn/qIkxTdgtvbSmndktHguWOMmj9aSVrK8U+0RLZvftA/bVkxeabYx0M7sjYTf3Ow/Y
1fIHQYnWg90DONnCqcULattjrbYT0n7yqnmRbT9515SVy3puJ/K7Mo9h9zbzlchgSydiad17YPde
Fjdz6kLyBbGMvc0vnSn58KgNSysLtf2jJsY0YfdejBrv2a2BXclDVAvsWvQJaYzsM9mpNgF2zwm7
qd96wm7vkWYEJVpGqaU5aSbs6BguKeymoCN/KH0ii1LaP9e4jSH7sYXU5K60xCqtey/sFu08WK6V
2ltTNwsfpiDt8aP3/yXxjaR/NMdr42kMyQ9KlM5JzrxkWerHJd/sHzJ79+tKMruafUISI9mjx47i
Adh1hd3a8ixgV/uUBekLcT0+A3bReYBX+NJFL+zmsorbSfpiT+5u8qpahi+UJcp8Zr74tj/uKLXU
WTMRS+quAbtH9S+9RCixt7ZuFj48AsIa30j6R02MbeuSWw4XPzRmtgQd1//+Hlpt2O05cqzUllZ9
ouWc3Yvf7be1ALvTwa7F6Qojjx7T3vdLUCIUBdQVJlV0PtUcP4eIEWJkTtjtgUlNoNT84IUE7LXq
RlAi5Kx9tjXi54ZRrIeh0tYMRIwQIzEgd/bPBZcgVuO0idp6tZRPcCLkPUFtl2bJvCBprAAxiBhB
SCScgBBCCCGEgF2EEEIIIYSAXYQQQgghhIBdhBBCCCGEgF2EwuroZRDJl6a67xv0mLLil6mEX6Ea
eZbn3aea02egpvx8z96EbaWv4+11c++LL4wl6lnVHoLzm0fYmvroRuokktw5uOoxK7QrF8dH7Vd7
jaRNJNcghIBdhMzA7v6XiYDdiLB7BB2pr3UdHsBfsC91XardtkfRpT5LLXmzXlo/D1tTJwakYHdb
rma899p1FMu59pNeI2kTyTUIIWAXoW5A2k8u20nc8rzcGT5A0QOso2D3Llt69yWurW9vQGT/VS7p
51a31+3LOgKlPVQlvzBW8WngbP2cbL39fc2DjzLMtdiVu07SfqI2lrSJ4BrGaYSAXYSaVfps8DUI
byecI3C7KOP51V9ul3Q3k+c+c3O4pP3m78+uXr64WBJOfRK38KnVbJnKwJqzLfXby/pd/eni8HwB
NOXquG2vO6C888++Pof1Eyy15z4JfQtBb+77+NGD/x75pRR7Wf8d1M/LVmmG+ugjCVqwK7VLep2k
/STXSNpEcg1jNULALkL9GaEdLNZMqqk9izfXpJZNbybG0peSkpm0zLJnqczajFFq8i3ZJoHd1u0R
ySzb5rdZuMm0eSrbd/SwceTL67pc+0DyMNVi71H9PG2VtN8tFH/04TdWe3Zr7MpdJ2k/yTWSNmlt
N4SAXYSQ6oQoht19hvVgqXr/ty34bWFimzk6WqreAsXdtdIy6zJG+Qk5/7cS7JZsligFHC2ZzJSP
UwCYq2sJdlsyeKn6ediafNBLZNiv//bFy+dPrWFXYpfkOkn2vRl239nfmm1HCNhFCPnArvCFoW0m
NrVnt2Z/4b6MVJmty6NHv5PYJoHdC5sb9y/X2JsDicsHl7KPbn2QuFYbdnP187A1uwT/7p6393l3
jTXISe2SXAfsIgTsIjS9tLcxpN64F8FuAWBzcLR/yWUa2M3YLDmloAt2c1lKYTyU4kcOu+X7lern
bWuqDfcvsNWAnOQ4wBof9VynDrtsY0AI2EVoCOwW4OrtRFRYkpfAbm6Cnj2zW9r/65nZlb78I4Gf
FijRyuxK6udhq6Rti0fY5bYZVMCuNuhqwC4vqCEE7CIUQpKjx3Jvs4smu0ym82Lf4Kbco/21LXt2
rWBX+rZ78QW1o2yx0p5d6bFOkrNfj47j0trGUHpgENXPwdaj6/YPZD2wWyPp+b015/x2wy5HjyEE
7CIURT0flShNiNqnMeS2DxydxmAFuxLbRLBbsFk68afOgS0d2J/6KELNBxlaQOiibpXZzdaPE1jY
WusTi/2oUrtq7NeAXUmbSK9BCAG7CJlMmJLPBUsmxNzh87kzZyXAINnWYAW7JdsksLs/BzgFU9Lt
EkfX5T7FKt17LCmrBoS2/5YrQ7N+VraWzlq2hl2pXbX2a8Cu1I98LhghYBchtNKDhcFX41IvvYX3
AfsyEUII2EUIAbsSSb/mFUGtH5RACCFgFyGETgq7N+VGf7Hn7uxZsroIIQTsIoQQQgghBOwihBBC
CCFgFyGEEEIIoQn1P5ltcdt9QzGLAAAAAElFTkSuQmCCUEsBAi0AFAAGAAgAAAAhAFqYrcIMAQAA
GAIAABMAAAAAAAAAAAAAAAAAAAAAAFtDb250ZW50X1R5cGVzXS54bWxQSwECLQAUAAYACAAAACEA
CMMYpNQAAACTAQAACwAAAAAAAAAAAAAAAAA9AQAAX3JlbHMvLnJlbHNQSwECLQAUAAYACAAAACEA
JsruMRECAAA9BQAAEgAAAAAAAAAAAAAAAAA6AgAAZHJzL3BpY3R1cmV4bWwueG1sUEsBAi0AFAAG
AAgAAAAhAKomDr68AAAAIQEAAB0AAAAAAAAAAAAAAAAAewQAAGRycy9fcmVscy9waWN0dXJleG1s
LnhtbC5yZWxzUEsBAi0AFAAGAAgAAAAhAHVomVASAQAAggEAAA8AAAAAAAAAAAAAAAAAcgUAAGRy
cy9kb3ducmV2LnhtbFBLAQItAAoAAAAAAAAAIQBI/rbhMRgAADEYAAAUAAAAAAAAAAAAAAAAALEG
AABkcnMvbWVkaWEvaW1hZ2UxLnBuZ1BLBQYAAAAABgAGAIQBAAAUHwAAAAA=
">
   <v:imagedata src="FIF%20RADANA%20MCF%20MEGA%20FINANCE_files/FIF%20RADANA%20MCF%20MEGA%20FINANCE_9033_image001.png"
    o:title=""/>
   <x:ClientData ObjectType="Pict">
    <x:SizeWithCells/>
    <x:CF>Bitmap</x:CF>
    <x:AutoPict/>
   </x:ClientData>
  </v:shape><v:shape id="Straight_x0020_Connector_x0020_3" o:spid="_x0000_s1098"
   type="#_x0000_t75" style='position:absolute;margin-left:2.25pt;margin-top:51pt;
   width:403.5pt;height:2.25pt;z-index:2;visibility:visible' o:gfxdata="UEsDBBQABgAIAAAAIQD+JeulAAEAAOoBAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbJSRzU7EIBDH
7ya+A+FqWqoHY0zpHqwe1Zj1AQhMW2I7EAbr7ts73e5ejGviEeb/8RuoN7tpFDMk8gG1vC4rKQBt
cB57Ld+3T8WdFJQNOjMGBC33QHLTXF7U230EEuxG0nLIOd4rRXaAyVAZIiBPupAmk/mYehWN/TA9
qJuqulU2YAbMRV4yZFO30JnPMYvHHV+vJAlGkuJhFS5dWpoYR29NZlI1o/vRUhwbSnYeNDT4SFeM
IdWvDcvkfMHR98JPk7wD8WpSfjYTYyiXaNkAweaQWFf+nbSgTlSErvMWyjYRL7V6T3DnSlz4wgTz
f/Nbtr3BfEpXh59qvgEAAP//AwBQSwMEFAAGAAgAAAAhAJYFM1jUAAAAlwEAAAsAAABfcmVscy8u
cmVsc6SQPWsDMQyG90L/g9He8yVDKSW+bIWsIYWuxtZ9kLNkJHNN/n1MoaVXsnWUXvQ8L9rtL2k2
C4pOTA42TQsGKXCcaHDwfnp7egGjxVP0MxM6uKLCvnt82B1x9qUe6ThlNZVC6mAsJb9aq2HE5LXh
jFSTniX5UkcZbPbh7Ae027Z9tvKbAd2KaQ7RgRziFszpmqv5DztNQVi5L03gZLnvp3CPaiN/0hGX
SvEyYHEQRb+WgktTy4G979380xuYCENh+aiOlfwnqfbvBnb1zu4GAAD//wMAUEsDBBQABgAIAAAA
IQAUETsABwIAANEFAAAUAAAAZHJzL2Nvbm5lY3RvcnhtbC54bWysVMFu2zAMvQ/YPwi6r3acucmM
2MWQorsMW9Fuu2u2FAuTKUMSHOfvR0m2MxTdgLXxSSYpvkc+UrubsVNk4MZKDSVdXaWUcKh1I+FQ
0u/f7t5tKbGOQcOUBl7SE7f0pnr7Zjc2pmBQt9oQTAG2QENJW+f6Ikls3fKO2Svdc0Cv0KZjDn/N
IWkMO2LyTiVZml4ntjecNbbl3N1GD61CbnfUe67UxwARTcLoLp5qrap0l3gO/hgu4OGrENV6u0rP
Lm8JXqOP1Tre8MfZ5v1TNJpDdMh6hnJ6SV9tn4f8P7gPeZYvRM6IC84Ijz3pWG10SadewLD31nsz
Ufky3Bsim5K+pwRYh7I8OsPkoXVkrwF47VCVNU2W8Ok6GkJ1T/LZkJkVozDdJCZ7gZQdk0CJULL/
gZOE1FmhhSBjSYMmlJxKep1vsiz3zFjBR0dq9OZpvtlsckpqDPDd8e4k0vFxvbHuE9evp+YTlVRJ
4IEcGz5bF6FmCA+n4LU98FmsVrK5kwqHE3/M4edeGTIwVdI0fFONf4RhxQomgaIifrytOykeaT1w
bGZYtZerIxtseBbKDzvKF1rNr9XESQEieUiB9C8Gmv4bdMLysFwInOCLAcdJ/Gu1C1qoWMPlgDsJ
2jxXtRvnVouIN6setY7Pml/4aX+V5OBumWPz/j55G8OF+BZXvwEAAP//AwBQSwMEFAAGAAgAAAAh
AKv2AtwRAQAAhQEAAA8AAABkcnMvZG93bnJldi54bWxcUMtOwzAQvCPxD9YicaMOhkAT4lQVEq8L
UkNA6s1KnAeN7cg2TeDr2dKiCI4zuzM7s8liVB3ZSutaozmczwIgUhembHXNIX+5O5sDcV7oUnRG
Sw6f0sEiPT5KRFyaQa/kNvM1QRPtYsGh8b6PKXVFI5VwM9NLjbPKWCU8QlvT0ooBzVVHWRBcUSVa
jRca0cvbRhab7ENxMM0rtQGLnu7rdb52m5w9vGdvnJ+ejMsbIF6Oflo+qB9LDpewq4I1IMV8Y7fU
RWMsqVbStV8Yfs9X1ihizcCBASlMxwFLI36uKic9bkVBGCCFo1+KzcPrEOjO1Zu99uKgxf/81/6R
RiH7UdIpUJogmL6XfgMAAP//AwBQSwECLQAUAAYACAAAACEA/iXrpQABAADqAQAAEwAAAAAAAAAA
AAAAAAAAAAAAW0NvbnRlbnRfVHlwZXNdLnhtbFBLAQItABQABgAIAAAAIQCWBTNY1AAAAJcBAAAL
AAAAAAAAAAAAAAAAADEBAABfcmVscy8ucmVsc1BLAQItABQABgAIAAAAIQAUETsABwIAANEFAAAU
AAAAAAAAAAAAAAAAAC4CAABkcnMvY29ubmVjdG9yeG1sLnhtbFBLAQItABQABgAIAAAAIQCr9gLc
EQEAAIUBAAAPAAAAAAAAAAAAAAAAAGcEAABkcnMvZG93bnJldi54bWxQSwUGAAAAAAQABAD5AAAA
pQUAAAAA
">
   <v:imagedata src="FIF%20RADANA%20MCF%20MEGA%20FINANCE_files/FIF%20RADANA%20MCF%20MEGA%20FINANCE_9033_image002.png"
    o:title=""/>
   <o:lock v:ext="edit" aspectratio="f"/>
   <x:ClientData ObjectType="Pict">
    <x:SizeWithCells/>
    <x:CF>Bitmap</x:CF>
    <x:AutoPict/>
   </x:ClientData>
  </v:shape><v:shape id="Straight_x0020_Connector_x0020_76" o:spid="_x0000_s1099"
   type="#_x0000_t75" style='position:absolute;margin-left:2.25pt;margin-top:52.5pt;
   width:403.5pt;height:2.25pt;z-index:3;visibility:visible' o:gfxdata="UEsDBBQABgAIAAAAIQD+JeulAAEAAOoBAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbJSRzU7EIBDH
7ya+A+FqWqoHY0zpHqwe1Zj1AQhMW2I7EAbr7ts73e5ejGviEeb/8RuoN7tpFDMk8gG1vC4rKQBt
cB57Ld+3T8WdFJQNOjMGBC33QHLTXF7U230EEuxG0nLIOd4rRXaAyVAZIiBPupAmk/mYehWN/TA9
qJuqulU2YAbMRV4yZFO30JnPMYvHHV+vJAlGkuJhFS5dWpoYR29NZlI1o/vRUhwbSnYeNDT4SFeM
IdWvDcvkfMHR98JPk7wD8WpSfjYTYyiXaNkAweaQWFf+nbSgTlSErvMWyjYRL7V6T3DnSlz4wgTz
f/Nbtr3BfEpXh59qvgEAAP//AwBQSwMEFAAGAAgAAAAhAJYFM1jUAAAAlwEAAAsAAABfcmVscy8u
cmVsc6SQPWsDMQyG90L/g9He8yVDKSW+bIWsIYWuxtZ9kLNkJHNN/n1MoaVXsnWUXvQ8L9rtL2k2
C4pOTA42TQsGKXCcaHDwfnp7egGjxVP0MxM6uKLCvnt82B1x9qUe6ThlNZVC6mAsJb9aq2HE5LXh
jFSTniX5UkcZbPbh7Ae027Z9tvKbAd2KaQ7RgRziFszpmqv5DztNQVi5L03gZLnvp3CPaiN/0hGX
SvEyYHEQRb+WgktTy4G979380xuYCENh+aiOlfwnqfbvBnb1zu4GAAD//wMAUEsDBBQABgAIAAAA
IQD7tADzDQIAANgFAAAUAAAAZHJzL2Nvbm5lY3RvcnhtbC54bWysVMFu2zAMvQ/YPwi6r3ZcOE6N
2MWQorsMW7Fuu2u2FAuTKUMSHOfvR0mOUxTdgLXxSSZFvkc+UtvbqVdk5MZKDRVdXaWUcGh0K2Ff
0R/f7z9sKLGOQcuUBl7RI7f0tn7/bju1pmTQdNoQTAG2RENFO+eGMkls0/Ge2Ss9cECv0KZnDn/N
PmkNO2DyXiVZmq4TOxjOWttx7u6ih9YhtzvoHVfqY4CIJmF0H0+NVnW6TTwHfwwBePgqRH29WaVn
l7cEr9GH+jpG+OPJ5v2rmzSfI9AVIkLmM5zTC0S9eRn2/yCzTV7kC5sz5AI0weNAetYYXdG5ITDu
vPXBzFy+jA+GyLaiRUEJsB7FeXSGyX3nyE4D8MahNsWaJkvAnAANocBnGW3IzcpJmH7WlL1C0Z5J
oEQoOfzEgULyrNRCkKmiQRpKjhVdF+usyD0zVvLJkQa9eZoXBRpJgxdu8iy4k0jH3xuMdZ+4fjs1
n6iiSgIP5Nj42TrfkjOEh1Pw1h74LFYr2d5LhTOKP2b/a6cMGZmqaBo+3wIEfnIN/xTMAkVF/JRb
d1Q80vrGsZlh416vjmyx4VkoP6wqX2i1v1czJwWI5CEF0r8YaPpv0BnLw3IhcIQvBhwn8a/VLmih
Yg2XA+4laPNS1W46tVpEvJPqUev4uvmVn/dXSQ7ujjl22t9nT2QIiE9y/QcAAP//AwBQSwMEFAAG
AAgAAAAhADS8epMTAQAAhAEAAA8AAABkcnMvZG93bnJldi54bWxUkEtPwzAQhO9I/AdrkbhRp6lC
0lCnqpB4XZAaAlJvVuI8aGxHtmkCv55toAocZ9fzeWZX60G25CCMbbRiMJ95QITKddGoikH2cncV
AbGOq4K3WgkGn8LCOjk/W/G40L3aikPqKoIQZWPOoHauiym1eS0ktzPdCYW7UhvJHUpT0cLwHuGy
pb7nXVPJG4U/1LwTt7XI9+mHZKDrV2o8f/l0X+2ynd1n/sN7+sbY5cWwuQHixOCmx7/ux4JBGMKx
C/aABAMO7UbltTak3ArbfGH6n3lptCRG9wwWQHLdMsDWqJ/L0grHYBn4wbg4DfwoCAOgR6bT/514
nj/ORTT3kIXMk3VkoZNOcUYxHS/5BgAA//8DAFBLAQItABQABgAIAAAAIQD+JeulAAEAAOoBAAAT
AAAAAAAAAAAAAAAAAAAAAABbQ29udGVudF9UeXBlc10ueG1sUEsBAi0AFAAGAAgAAAAhAJYFM1jU
AAAAlwEAAAsAAAAAAAAAAAAAAAAAMQEAAF9yZWxzLy5yZWxzUEsBAi0AFAAGAAgAAAAhAPu0APMN
AgAA2AUAABQAAAAAAAAAAAAAAAAALgIAAGRycy9jb25uZWN0b3J4bWwueG1sUEsBAi0AFAAGAAgA
AAAhADS8epMTAQAAhAEAAA8AAAAAAAAAAAAAAAAAbQQAAGRycy9kb3ducmV2LnhtbFBLBQYAAAAA
BAAEAPkAAACtBQAAAAA=
">
   <v:imagedata src="FIF%20RADANA%20MCF%20MEGA%20FINANCE_files/FIF%20RADANA%20MCF%20MEGA%20FINANCE_9033_image002.png"
    o:title=""/>
   <o:lock v:ext="edit" aspectratio="f"/>
   <x:ClientData ObjectType="Pict">
    <x:SizeWithCells/>
    <x:CF>Bitmap</x:CF>
    <x:AutoPict/>
   </x:ClientData>
  </v:shape><![endif]--><![if !vml]><span style='mso-ignore:vglayout;
  position:absolute;z-index:1;margin-left:3px;margin-top:6px;width:538px;
  height:67px'><img width=538 height=67
  src="report/FIF%20RADANA%20MCF%20MEGA%20FINANCE_files/FIF%20RADANA%20MCF%20MEGA%20FINANCE_9033_image003.png"
  v:shapes="Picture_x0020_1 Straight_x0020_Connector_x0020_3 Straight_x0020_Connector_x0020_76"></span><![endif]><span
  style='mso-ignore:vglayout2'>
  <table cellpadding=0 cellspacing=0>
 	<?php
		$i=1;
		if($data !=0){
		foreach ($data as $value) {
		extract($value);
	?> 
   <tr>
    <td height=27 class=xl159033 width=31 style='height:20.25pt;width:23pt'></td>
   </tr>
  </table>
  </span></td>
  <td class=xl159033 width=91 style='width:68pt'></td>
  <td colspan=6 class=xl659033 width=418 style='width:314pt'><span
  style='mso-spacerun:yes'> </span>MITRA UTAMA MOTOR<span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl639033 width=93 style='width:70pt'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl159033 style='height:15.75pt'></td>
  <td class=xl159033></td>
  <td colspan=6 class=xl669033>Jl. Raya Sunan Gunung Jati No. 47 Tangkil
  Cirebon</td>
  <td class=xl159033></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl159033 style='height:15.75pt'></td>
  <td class=xl159033></td>
  <td colspan=6 class=xl669033>(0231) 202534, 221100</td>
  <td class=xl159033></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl159033 style='height:15.0pt'></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
 </tr>
 
 <tr height=20 style='height:15.0pt'>
  <td colspan=8 height=20 class=xl679033 style='height:15.0pt'>SURAT PERNYATAAN</td>
  <td class=xl159033></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td colspan=8 height=20 class=xl649033 style='height:15.0pt'>Yang bertanda
  tangan dibawah ini:</td>
  <td class=xl159033></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl649033 style='height:15.0pt'></td>
  <td class=xl649033>Nama</td>
  <td colspan=6 class=xl649033>: LILIS</td>
  <td class=xl159033></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl649033 style='height:15.0pt'></td>
  <td class=xl649033>Jabatan</td>
  <td colspan=6 class=xl649033>: ADM</td>
  <td class=xl639033></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl649033 style='height:15.0pt'></td>
  <td class=xl649033>Alamat</td>
  <td colspan=6 class=xl649033>: JL. RAYA SUNAN GUNUNGJATI NO 47 CIREBON</td>
  <td class=xl639033></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl649033 style='height:15.0pt'></td>
  <td class=xl649033>Telepon</td>
  <td colspan=6 class=xl649033>: (0231) 221100</td>
  <td class=xl159033></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl649033 style='height:15.0pt'></td>
  <td class=xl649033></td>
  <td class=xl649033></td>
  <td class=xl649033></td>
  <td class=xl649033></td>
  <td class=xl699033></td>
  <td class=xl699033></td>
  <td class=xl699033></td>
  <td class=xl159033></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td colspan=8 height=20 class=xl649033 style='height:15.0pt'>Menyatakan
  Kendaraan dengan data dibawah ini<span style='mso-spacerun:yes'> </span></td>
  <td class=xl159033></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl649033 style='height:15.0pt'></td>
  <td class=xl649033>Atas Nama</td>
  <td colspan=6 class=xl649033>: <?php echo $cusname ?></td>
  <td class=xl159033></td>
 </tr>
 <tr height=42 style='mso-height-source:userset;height:31.5pt'>
  <td height=42 class=xl649033 style='height:31.5pt'></td>
  <td class=xl709033>Alamat</td>
  <td colspan=6 class=xl719033 width=418 style='width:314pt'>: <?php echo $address ?> <?php echo $villagename ?> <?php echo $districtsname ?> <?php echo $cityname ?></td>
  <td class=xl159033></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl649033 style='height:15.0pt'></td>
  <td class=xl649033>Merek/Type</td>
  <td colspan=6 class=xl649033>: HONDA / <?php echo $vehicletype ?></td>
  <td class=xl159033></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl649033 style='height:15.0pt'></td>
  <td class=xl649033>No. Rangka</td>
  <td colspan=6 class=xl649033>: <?php echo $rangkano ?></td>
  <td class=xl159033></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl649033 style='height:15.0pt'></td>
  <td class=xl649033>No. Mesin</td>
  <td colspan=6 class=xl649033>: <?php echo $mechineno ?></td>
  <td class=xl159033></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl649033 style='height:15.0pt'></td>
  <td class=xl649033>Warna</td>
  <td colspan=6 class=xl649033>: <?php echo $vehiclecolorname ?></td>
  <td class=xl159033></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl649033 style='height:15.0pt'></td>
  <td class=xl649033>Tahun</td>
  <td colspan=6 class=xl649033>: <?php echo $year ?></td>
  <td class=xl159033></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl159033 style='height:15.0pt'></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
 </tr>
 <tr height=43 style='mso-height-source:userset;height:32.25pt'>
  <td colspan=8 height=43 class=xl719033 width=540 style='height:32.25pt;
  width:405pt'>Akan kami serahkan BPKB beserta Faktur kendaraan tersebut diatas
  selambat-lambatnya 180 (Seratus delapan puluh) hari dari tanggal STNK
  kendaraan tersebut kepada:</td>
  <td class=xl159033></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl159033 style='height:15.0pt'></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td colspan=8 height=20 class=xl649033 style='height:15.0pt'>Demikian Surat
  Pernyataan ini kami buat untuk digunakan seperlunya.</td>
  <td class=xl159033></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl689033 style='height:15.0pt'></td>
  <td class=xl689033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td colspan=8 height=20 class=xl649033 style='height:15.0pt'>Cirebon, 18
  November 2016</td>
  <td class=xl159033></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl689033 style='height:15.0pt'></td>
  <td class=xl689033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl689033 style='height:15.0pt'></td>
  <td class=xl689033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl689033 style='height:15.0pt'></td>
  <td class=xl689033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
  <td class=xl159033></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
 
  <td colspan=8 height=20 class=xl649033 style='height:15.0pt'>LILIS</td>
  <td class=xl159033></td>
 </tr> 
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=31 style='width:23pt'></td>
  <td width=91 style='width:68pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=81 style='width:61pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=81 style='width:61pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=93 style='width:70pt'></td>
 </tr>
 
<?php
	$i++;
		}
		}
 ?>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>
 
</html>
