<?php
	$db=new Database();
	$rptdatefrom = $_POST['rptdatefrom'];
	$rptdateto = $_POST['rptdateto'];
	//error_reporting(0);
	$rptaroutstanding = new Rptaroutstanding();
	$core=new Core();
	$data = $rptaroutstanding->show($rptdatefrom, $rptdateto);
	extract($data);
	
	$datatotal = $rptaroutstanding->showtotal($rptdatefrom, $rptdateto);
	extract($datatotal);
?>


<style type="text/css">
    table { page-break-inside:auto }
    tr    { page-break-inside:avoid; page-break-after:auto }
    thead { display:table-header-group }
    tfoot { display:table-footer-group }
	
<!--	@media print {
  <!-- thead {display: table-header-group;}
<!-- }
</style>

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link rel=File-List href="AR%20Outstanding_files/filelist.xml">
<style id="AR Outstanding_26486_Styles">
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
.xl6326486
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:18.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6426486
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6526486
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6626486
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:9.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6726486
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:9.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6826486
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:10.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	background:#BFBFBF;
	mso-pattern:black none;
	white-space:normal;}
-->
</style>
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="AR Outstanding_26486" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=1548 class=xl6426486
 style='border-collapse:collapse;table-layout:fixed;width:1162pt'>
 <col class=xl6426486 width=92 span=2 style='mso-width-source:userset;
 mso-width-alt:3364;width:69pt'>
 <col class=xl6426486 width=167 style='mso-width-source:userset;mso-width-alt:
 6107;width:125pt'>
 <col class=xl6426486 width=284 style='mso-width-source:userset;mso-width-alt:
 10386;width:213pt'>
 <col class=xl6426486 width=170 style='mso-width-source:userset;mso-width-alt:
 6217;width:128pt'>
 <col class=xl6426486 width=114 style='mso-width-source:userset;mso-width-alt:
 4169;width:86pt'>
 <col class=xl6426486 width=100 style='mso-width-source:userset;mso-width-alt:
 3657;width:75pt'>
 <col class=xl6426486 width=120 style='mso-width-source:userset;mso-width-alt:
 4388;width:90pt'>
 <col class=xl6426486 width=106 style='mso-width-source:userset;mso-width-alt:
 3876;width:80pt'>
 <col class=xl6426486 width=111 style='mso-width-source:userset;mso-width-alt:
 4059;width:83pt'>
 <col class=xl6426486 width=96 span=2 style='mso-width-source:userset;
 mso-width-alt:3510;width:72pt'>
 <tr height=31 style='mso-height-source:userset;height:23.25pt'>
  <td colspan=3 height=31 class=xl6326486 width=351 style='height:23.25pt;
  width:263pt'>MITRA UTAMA MOTOR</td>
  <td class=xl6426486 width=284 style='width:213pt'></td>
  <td class=xl6426486 width=170 style='width:128pt'></td>
  <td class=xl6426486 width=114 style='width:86pt'></td>
  <td class=xl6426486 width=100 style='width:75pt'></td>
  <td class=xl6426486 width=120 style='width:90pt'></td>
  <td class=xl6426486 width=106 style='width:80pt'></td>
  <td class=xl6426486 width=111 style='width:83pt'></td>
  <td class=xl6426486 width=96 style='width:72pt'></td>
  <td class=xl6426486 width=96 style='width:72pt'></td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td colspan=6 height=20 class=xl6526486 width=919 style='height:15.0pt;
  width:690pt'>LAPORAN TAGIH BELUM CAIR</td>
  <td class=xl6426486 width=100 style='width:75pt'></td>
  <td class=xl6426486 width=120 style='width:90pt'></td>
  <td class=xl6426486 width=106 style='width:80pt'></td>
  <td class=xl6426486 width=111 style='width:83pt'></td>
  <td class=xl6426486 width=96 style='width:72pt'></td>
  <td class=xl6426486 width=96 style='width:72pt'></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td colspan=6 height=20 class=xl6526486 width=919 style='height:15.0pt;
  width:690pt'>PERIODE : <?php echo $rptdatefrom; ?> SAMPAI <?php echo $rptdateto; ?></td>
  <td class=xl6426486 width=100 style='width:75pt'></td>
  <td class=xl6426486 width=120 style='width:90pt'></td>
  <td class=xl6426486 width=106 style='width:80pt'></td>
  <td class=xl6426486 width=111 style='width:83pt'></td>
  <td class=xl6426486 width=96 style='width:72pt'></td>
  <td class=xl6426486 width=96 style='width:72pt'></td>
 </tr>
 <?php
		$i=1;
		if($datatotal !=0){
		foreach ($datatotal as $value123) {
		extract($value123);
	?>
 <tr height=20 style='height:15.0pt'>
  <td colspan=6 height=20 class=xl6526486 width=919 style='height:15.0pt;
  width:690pt'>JUMLAH UNIT : <?php echo number_format($tunit); ?> </td>
  <td class=xl6426486 width=100 style='width:75pt'></td>
  <td class=xl6426486 width=120 style='width:90pt'></td>
  <td class=xl6426486 width=106 style='width:80pt'></td>
  <td class=xl6426486 width=111 style='width:83pt'></td>
  <td class=xl6426486 width=96 style='width:72pt'></td>
  <td class=xl6426486 width=96 style='width:72pt'></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td colspan=6 height=20 class=xl6526486 width=919 style='height:15.0pt;
  width:690pt'>TOTAL : <?php echo number_format($ttagih); ?> </td>
  <td class=xl6426486 width=100 style='width:75pt'></td>
  <td class=xl6426486 width=120 style='width:90pt'></td>
  <td class=xl6426486 width=106 style='width:80pt'></td>
  <td class=xl6426486 width=111 style='width:83pt'></td>
  <td class=xl6426486 width=96 style='width:72pt'></td>
  <td class=xl6426486 width=96 style='width:72pt'></td>
 </tr>
 <?php
	$i++;
		}
		} 
    ?>
 <tr height=34 style='mso-height-source:userset;height:25.5pt'>
  <td height=34 class=xl6826486 width=92 style='height:25.5pt;width:69pt'>TGL
  JUAL</td>
  <td class=xl6826486 width=92 style='border-left:none;width:69pt'>TGL TAGIH</td>
  <td class=xl6826486 width=167 style='border-left:none;width:125pt'>NAMA</td>
  <td class=xl6826486 width=284 style='border-left:none;width:213pt'>TYPE</td>
  <td class=xl6826486 width=170 style='border-left:none;width:128pt'>NO MESIN</td>
  <td class=xl6826486 width=114 style='border-left:none;width:86pt'>OTR</td>
  <td class=xl6826486 width=100 style='border-left:none;width:75pt'>TAGIH</td>
  <td class=xl6826486 width=120 style='border-left:none;width:90pt'>LEASING</td>
  <td class=xl6826486 width=106 style='border-left:none;width:80pt'>NO. PO</td>
  <td class=xl6826486 width=111 style='border-left:none;width:83pt'>SALES</td>
  <td class=xl6826486 width=96 style='border-left:none;width:72pt'>LEAD 
  JUAL</td>
  <td class=xl6826486 width=96 style='border-left:none;width:72pt'>LEAD 
  TAGIH</td>
 </tr>
 <?php
		$i=1;
		if($data !=0){
		foreach ($data as $value) {
		extract($value);
	?>
    
 <tr class=xl6626486 height=16 style='height:12.0pt'>
  <td height=16 class=xl6726486 width=92 style='height:12.0pt;border-top:none;
  width:69pt'>
  <?php echo $datetrans; ?></td>
  <td class=xl6726486 width=92 style='border-top:none;border-left:none;
  width:69pt'><?php echo $arbillingdate; ?></td>
  <td class=xl6726486 width=167 style='border-top:none;border-left:none;
  width:125pt'><?php echo $cusname; ?></td>
  <td class=xl6726486 width=284 style='border-top:none;border-left:none;
  width:213pt'><?php echo $vehicletypesw; ?> - <?php echo $vehiclemodelsw; ?></td>
  <td class=xl6726486 width=170 style='border-top:none;border-left:none;
  width:128pt'><?php echo $mechineno; ?></td>
  <td class=xl6726486 width=114 style='border-top:none;border-left:none;
  width:86pt'><?php echo $otrsw; ?></td>
  <td class=xl6726486 width=100 style='border-top:none;border-left:none;
  width:75pt'><?php echo $penagihansw; ?></td>
  <td class=xl6726486 width=120 style='border-top:none;border-left:none;
  width:90pt'><?php echo $leasing; ?></td>
  <td class=xl6726486 width=106 style='border-top:none;border-left:none;
  width:80pt'><?php echo $pono; ?></td>
  <td class=xl6726486 width=111 style='border-top:none;border-left:none;
  width:83pt'><?php echo $salesmanname; ?></td>
  <td class=xl6726486 width=96 style='border-top:none;border-left:none;
  width:72pt'><?php echo $leadsales; ?></td>
  <td class=xl6726486 width=96 style='border-top:none;border-left:none;
  width:72pt'><?php echo $leadar; ?></td>
 </tr>
 <?php
	$i++;
		}
		} 
    ?>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=92 style='width:69pt'></td>
  <td width=92 style='width:69pt'></td>
  <td width=167 style='width:125pt'></td>
  <td width=284 style='width:213pt'></td>
  <td width=170 style='width:128pt'></td>
  <td width=114 style='width:86pt'></td>
  <td width=100 style='width:75pt'></td>
  <td width=120 style='width:90pt'></td>
  <td width=106 style='width:80pt'></td>
  <td width=111 style='width:83pt'></td>
  <td width=96 style='width:72pt'></td>
  <td width=96 style='width:72pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>
