<?php
	$db=new Database();
	$rptdatefrom = $_POST['rptdatefrom'];
	$rptdateto = $_POST['rptdateto'];
	//error_reporting(0);
	$rptpurchasevehicle = new Rptpurchasevehicle();
	$core=new Core();
	$data = $rptpurchasevehicle->show($rptdatefrom, $rptdateto);
	extract($data);
?>


<style type="text/css">
    table { page-break-inside:auto }
    tr    { page-break-inside:avoid; page-break-after:auto }
    thead { display:table-header-group }
    tfoot { display:table-footer-group }
	
<!--	@media print {
  <!-- thead {display: table-header-group;}
<!-- }
</style>

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link rel=File-List href="Pembelian_files/filelist.xml">
<style id="Penjualan Channel_17761_Styles"><!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
.xl6317761
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6417761
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6517761
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:18.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6617761
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:bottom;
	border-top:none;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6717761
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	background:#BFBFBF;
	mso-pattern:black none;
	white-space:nowrap;}
.xl6817761
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:bottom;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
--></style>
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="Penjualan Channel_17761" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=925 class=xl6317761
 style='border-collapse:collapse;table-layout:fixed;width:696pt'>
 <col class=xl6317761 width=94 style='mso-width-source:userset;mso-width-alt:
 3437;width:71pt'>
 <col class=xl6317761 width=113 style='mso-width-source:userset;mso-width-alt:
 4132;width:85pt'>
 <col class=xl6317761 width=201 style='mso-width-source:userset;mso-width-alt:
 7350;width:151pt'>
 <col class=xl6317761 width=138 span=2 style='mso-width-source:userset;

 mso-width-alt:5046;width:104pt'>
 <col class=xl6317761 width=77 style='mso-width-source:userset;mso-width-alt:
 2816;width:58pt'>
 <col class=xl6317761 width=164 style='mso-width-source:userset;mso-width-alt:
 5997;width:123pt'>
  <col class=xl6317761 width=164 style='mso-width-source:userset;mso-width-alt:
 5997;width:123pt'>
 <tr height=31 style='mso-height-source:userset;height:23.25pt'>
  <td colspan=7 height=31 class=xl6517761 width=925 style='height:23.25pt;
  width:696pt'>MITRA UTAMA MOTOR</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td colspan=7 height=20 class=xl6417761 width=925 style='height:15.0pt;
  width:696pt'>LAPORAN PEMBELIAN UNIT</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td colspan=8 height=20 class=xl6617761 width=925 style='height:15.0pt;
  width:696pt'>PERIODE : <?php echo $rptdatefrom; ?> SAMPAI <?php echo $rptdateto; ?></td>
 </tr>
 
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6717761 style='height:15.0pt;border-top:none'>TANGGAL</td>
  <td class=xl6717761 style='border-top:none;border-left:none'>NO DO</td>
  <td class=xl6717761 style='border-top:none;border-left:none'>TYPE</td>
  <td class=xl6717761 style='border-top:none;border-left:none'>NO MESIN</td>
  <td class=xl6717761 style='border-top:none;border-left:none'>WARNA</td>
  <td class=xl6717761 style='border-top:none;border-left:none'>TAHUN</td>
  <td class=xl6717761 style='border-top:none;border-left:none'>HARGA</td>
  <td class=xl6717761 style='border-top:none;border-left:none'>LOKASI</td>
 </tr>
 <?php
		$i=1;
		if($data !=0){
		foreach ($data as $value) {
		extract($value);
	?>
 <tr class=xl6417761 height=20 style='height:15.0pt'>
  <td height=20 class=xl6817761 style='height:15.0pt;border-top:none'><?php echo $dodate; ?></td>
  <td class=xl6817761 style='border-top:none;border-left:none'><?php echo $dono; ?></td>
  <td class=xl6817761 style='border-top:none;border-left:none'><?php echo $vehicletype; ?></td>
  <td class=xl6817761 style='border-top:none;border-left:none'><?php echo $mechineno; ?></td>
  <td class=xl6817761 style='border-top:none;border-left:none'><?php echo $vehiclecolor; ?></td>
  <td class=xl6817761 style='border-top:none;border-left:none'><?php echo $year; ?></td>
  <td class=xl6817761 style='border-top:none;border-left:none'><?php echo $unitprice; ?></td>
  <td class=xl6817761 style='border-top:none;border-left:none'><?php echo $channelname; ?></td>
 </tr>
 <?php
	$i++;
		}
		} 
    ?>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=94 style='width:71pt'></td>
  <td width=113 style='width:85pt'></td>
  <td width=201 style='width:151pt'></td>
  <td width=138 style='width:104pt'></td>
  <td width=138 style='width:104pt'></td>
  <td width=77 style='width:58pt'></td>
  <td width=164 style='width:123pt'></td>
   <td width=164 style='width:123pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>


