<?php
	$db=new Database();
	$rptdatefrom = $_POST['rptdatefrom'];
	$rptdateto = $_POST['rptdateto'];
	//error_reporting(0);
	$rptsalessuspend = new Rptsalessuspend();
	$core=new Core();
	$data = $rptsalessuspend->show($rptdatefrom, $rptdateto);
	extract($data);
?>


<style type="text/css">
    table { page-break-inside:auto }
    tr    { page-break-inside:avoid; page-break-after:auto }
    thead { display:table-header-group }
    tfoot { display:table-footer-group }
	
<!--	@media print {
  <!-- thead {display: table-header-group;}
<!-- }
</style>

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link rel=File-List href="Penjualan%20Suspend_files/filelist.xml">
<style id="Penjualan Detail_14570_Styles"><!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
.xl1514570
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6514570
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6614570
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:18.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6714570
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6814570
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6914570
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	background:#F2F2F2;
	mso-pattern:black none;
	white-space:nowrap;}
--></style>
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="Penjualan Detail_14570" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=2173 class=xl6514570
 style='border-collapse:collapse;table-layout:fixed;width:1633pt'>
 <col class=xl6514570 width=82 style='mso-width-source:userset;mso-width-alt:
 2998;width:62pt'>
 <col class=xl6514570 width=233 style='mso-width-source:userset;mso-width-alt:
 8521;width:175pt'>
 <col class=xl6514570 width=416 style='mso-width-source:userset;mso-width-alt:
 15213;width:312pt'>
 <col class=xl6514570 width=118 span=2 style='mso-width-source:userset;
 mso-width-alt:4315;width:89pt'>
 <col class=xl6514570 width=125 style='mso-width-source:userset;mso-width-alt:
 4571;width:94pt'>
 <col class=xl6514570 width=108 style='mso-width-source:userset;mso-width-alt:
 3949;width:81pt'>
 <col class=xl6514570 width=113 style='mso-width-source:userset;mso-width-alt:
 4132;width:85pt'>
 <col class=xl6514570 width=81 span=3 style='mso-width-source:userset;
 mso-width-alt:2962;width:61pt'>
 <col class=xl6514570 width=96 style='mso-width-source:userset;mso-width-alt:
 3510;width:72pt'>
 <col class=xl6514570 width=113 style='mso-width-source:userset;mso-width-alt:
 4132;width:85pt'>
 <col class=xl6514570 width=115 style='mso-width-source:userset;mso-width-alt:
 4205;width:86pt'>
 <col class=xl6514570 width=56 style='mso-width-source:userset;mso-width-alt:
 2048;width:42pt'>
 <col class=xl6514570 width=59 style='mso-width-source:userset;mso-width-alt:
 2157;width:44pt'>
 <col class=xl6514570 width=68 style='mso-width-source:userset;mso-width-alt:
 2486;width:51pt'>
 <col class=xl6514570 width=110 style='mso-width-source:userset;mso-width-alt:
 4022;width:83pt'>
 <tr height=29 style='mso-height-source:userset;height:21.75pt'>
  <td colspan=18 height=29 class=xl6614570 width=2173 style='height:21.75pt;
  width:1633pt'>MITRA UTAMA MOTOR</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td colspan=18 height=20 class=xl6714570 width=2173 style='height:15.0pt;
  width:1633pt'>LAPORAN PENJUALAN KENDARAAN SUSPEND</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td colspan=18 height=20 class=xl6714570 width=2173 style='height:15.0pt;
  width:1633pt'>PERIODE : <?php echo $rptdatefrom; ?> SAMPAI <?php echo $rptdateto; ?></td>
 </tr>
 <tr height=23 style='mso-height-source:userset;height:17.25pt'>
  <td height=23 class=xl6914570 style='height:17.25pt'>
  <form name=form1 id=form1 action=susp.aspx method=post>
  <span lang=en-us>TGL JUAL</td>
  <td class=xl6914570 style='border-left:none'>NAMA</td>
  <td class=xl6914570 style='border-left:none'>TYPE</td>
  <td class=xl6914570 style='border-left:none'>NO MESIN</td>
  <td class=xl6914570 style='border-left:none'>CARA BAYAR</td>
  <td class=xl6914570 style='border-left:none'>SALES</td>
  <td class=xl6914570 style='border-left:none'>POS</td>
  <td class=xl6914570 style='border-left:none'>TGL BAYAR</td>
  <td class=xl6914570 style='border-left:none'>TOTAL</td>
  <td class=xl6914570 style='border-left:none'>BAYAR</td>
  <td class=xl6914570 style='border-left:none'>SISA</td>
  <td class=xl6914570 style='border-left:none'>ID SALES</td>
  <td class=xl1514570></td>
  <td class=xl1514570></td>
  <td class=xl1514570></td>
  <td class=xl1514570></td>
  <td class=xl1514570></td>
  <td class=xl1514570></td>
 </tr>
 <?php
	$i=1;
	if($data !=0){
	foreach ($data as $value) {
	extract($value);
  ?>
  
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6814570 style='height:15.0pt;border-top:none'><?php echo $datetrans1; ?></td>
  <td class=xl6814570 style='border-top:none;border-left:none'><?php echo $cusname; ?></td>
  <td class=xl6814570 style='border-top:none;border-left:none'><?php echo $vehicletypesw; ?> - <?php echo $vehiclemodelsw; ?></td>
  <td class=xl6814570 style='border-top:none;border-left:none'><?php echo $mechineno; ?></td>
  <td class=xl6814570 style='border-top:none;border-left:none'><?php echo $leasing; ?></td>
  <td class=xl6814570 style='border-top:none;border-left:none'><?php echo $salesmanname; ?></td>
  <td class=xl6814570 style='border-top:none;border-left:none'><?php echo $channelname; ?></td>
  <td class=xl6814570 style='border-top:none;border-left:none'><?php echo $datebayar; ?></td>
  <td class=xl6814570 style='border-top:none;border-left:none'><?php echo $totaltagihan; ?></td>
  <td class=xl6814570 style='border-top:none;border-left:none'><?php echo $totalbayar; ?></td>
  <td class=xl6814570 style='border-top:none;border-left:none'><?php echo $sisabayar; ?></td>
  <td class=xl6814570 align=right style='border-top:none;border-left:none'><?php echo $nik; ?></span>
  </form>
  </td>
  <td class=xl1514570></td>
  <td class=xl1514570></td>
  <td class=xl1514570></td>
  <td class=xl1514570></td>
  <td class=xl1514570></td>
  <td class=xl1514570></td>
 </tr>
  <?php
	$i++;
		}
		} 
    ?>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=82 style='width:62pt'></td>
  <td width=233 style='width:175pt'></td>
  <td width=416 style='width:312pt'></td>
  <td width=118 style='width:89pt'></td>
  <td width=118 style='width:89pt'></td>
  <td width=125 style='width:94pt'></td>
  <td width=108 style='width:81pt'></td>
  <td width=113 style='width:85pt'></td>
  <td width=81 style='width:61pt'></td>
  <td width=81 style='width:61pt'></td>
  <td width=81 style='width:61pt'></td>
  <td width=96 style='width:72pt'></td>
  <td width=113 style='width:85pt'></td>
  <td width=115 style='width:86pt'></td>
  <td width=56 style='width:42pt'></td>
  <td width=59 style='width:44pt'></td>
  <td width=68 style='width:51pt'></td>
  <td width=110 style='width:83pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>





