<?php
	$db=new Database();
	$rptdatefrom = $_POST['rptdatefrom'];
	$rptdateto = $_POST['rptdateto'];
	//error_reporting(0);
	$rpttgllahir = new Rpttgllahir();
	$core=new Core();
	$data = $rpttgllahir->show($rptdatefrom, $rptdateto);
	extract($data);
?>


<style type="text/css">
    table { page-break-inside:auto }
    tr    { page-break-inside:avoid; page-break-after:auto }
    thead { display:table-header-group }
    tfoot { display:table-footer-group }
	
<!--	@media print {
  <!-- thead {display: table-header-group;}
<!-- }
</style>

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link rel=File-List href="Tanggal%20Lahir_files/filelist.xml">
<style id="Penjualan Channel_17761_Styles"><!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
.xl6317761
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6417761
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6517761
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:18.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6617761
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:9.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6717761
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:8.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6817761
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:bottom;
	border-top:none;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6917761
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:10.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	background:#BFBFBF;
	mso-pattern:black none;
	white-space:normal;}
--></style>
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="Penjualan Channel_17761" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=1362 class=xl6317761
 style='border-collapse:collapse;table-layout:fixed;width:1024pt'>
 <col class=xl6317761 width=154 style='mso-width-source:userset;mso-width-alt:
 5632;width:116pt'>
 <col class=xl6317761 width=164 style='mso-width-source:userset;mso-width-alt:
 5997;width:123pt'>
 <col class=xl6317761 width=93 style='mso-width-source:userset;mso-width-alt:
 3401;width:70pt'>
 <col class=xl6317761 width=466 style='mso-width-source:userset;mso-width-alt:
 17042;width:350pt'>
 <col class=xl6317761 width=90 style='mso-width-source:userset;mso-width-alt:
 3291;width:68pt'>
 <col class=xl6317761 width=165 style='mso-width-source:userset;mso-width-alt:
 6034;width:124pt'>
 <col class=xl6317761 width=79 style='mso-width-source:userset;mso-width-alt:
 2889;width:59pt'>
 <col class=xl6317761 width=90 style='mso-width-source:userset;mso-width-alt:
 3291;width:68pt'>
 <col class=xl6317761 width=61 style='mso-width-source:userset;mso-width-alt:
 2230;width:46pt'>
 <tr height=31 style='height:23.25pt'>
  <td colspan=2 height=31 class=xl6517761 width=318 style='height:23.25pt;
  width:239pt'>MITRA UTAMA MOTOR</td>
  <td class=xl6317761 width=93 style='width:70pt'></td>
  <td class=xl6317761 width=466 style='width:350pt'></td>
  <td class=xl6317761 width=90 style='width:68pt'></td>
  <td class=xl6317761 width=165 style='width:124pt'></td>
  <td class=xl6317761 width=79 style='width:59pt'></td>
  <td class=xl6317761 width=90 style='width:68pt'></td>
  <td class=xl6317761 width=61 style='width:46pt'></td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td colspan=6 height=20 class=xl6417761 width=1132 style='height:15.0pt;
  width:851pt'>LAPORAN TANGGAL LAHIR KONSUMEN</td>
  <td class=xl6317761 width=79 style='width:59pt'></td>
  <td class=xl6317761 width=90 style='width:68pt'></td>
  <td class=xl6317761 width=61 style='width:46pt'></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td colspan=6 height=20 class=xl6817761 width=1132 style='height:15.0pt;
  width:851pt'>PERIODE : <?php echo $rptdatefrom; ?> SAMPAI <?php echo $rptdateto; ?></td>
  <td class=xl6317761 width=79 style='width:59pt'></td>
  <td class=xl6317761 width=90 style='width:68pt'></td>
  <td class=xl6317761 width=61 style='width:46pt'></td>
 </tr>
 <tr height=22 style='mso-height-source:userset;height:16.5pt'>
  <td height=22 class=xl6917761 width=154 style='height:16.5pt;border-top:none;
  width:116pt'>NAMA PEMOHON</td>
  <td class=xl6917761 width=164 style='border-top:none;border-left:none;
  width:123pt'>NAMA STNK</td>
  <td class=xl6917761 width=93 style='border-top:none;border-left:none;
  width:70pt'>TGL LAHIR</td>
  <td class=xl6917761 width=466 style='border-top:none;border-left:none;
  width:350pt'>ALAMAT</td>
  <td class=xl6917761 width=90 style='border-top:none;border-left:none;
  width:68pt'>HP</td>
  <td class=xl6917761 width=165 style='border-top:none;border-left:none;
  width:124pt'>MODEL</td>
  <td class=xl6917761 width=79 style='border-left:none;width:59pt'>TGL BELI</td>
  <td class=xl6917761 width=90 style='border-left:none;width:68pt'>LEASING</td>
  <td class=xl6917761 width=61 style='border-left:none;width:46pt'>TENOR</td>
 </tr>
  <?php
		$i=1;
		if($data !=0){
		foreach ($data as $value) {
		extract($value);
	?>
 <tr class=xl6417761 height=20 style='height:15.0pt'>
  <td height=20 class=xl6617761 width=154 style='height:15.0pt;border-top:none;
  width:116pt'><?php echo $cusname; ?></td>
  <td class=xl6617761 width=164 style='border-top:none;border-left:none;
  width:123pt'><?php echo $bpkbname; ?></td>
  <td class=xl6617761 width=93 style='border-top:none;border-left:none;
  width:70pt'><?php echo $datebirth; ?></td>
  <td class=xl6717761 width=466 style='border-top:none;border-left:none;
  width:350pt'><?php echo $address; ?></td>
  <td class=xl6617761 width=90 style='border-top:none;border-left:none;
  width:68pt'><?php echo $handphone; ?></td>
  <td class=xl6617761 width=165 style='border-top:none;border-left:none;
  width:124pt'><?php echo $vehiclemodel; ?></td>
  <td class=xl6617761 width=79 style='border-top:none;border-left:none;
  width:59pt'><?php echo $datetrans; ?></td>
  <td class=xl6617761 width=90 style='border-top:none;border-left:none;
  width:68pt'><?php echo $leasing; ?></td>
  <td class=xl6617761 width=61 style='border-top:none;border-left:none;
  width:46pt'><?php echo $credittenor; ?></td>
 </tr>
  <?php
	$i++;
		}
		} 
    ?>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=154 style='width:116pt'></td>
  <td width=164 style='width:123pt'></td>
  <td width=93 style='width:70pt'></td>
  <td width=466 style='width:350pt'></td>
  <td width=90 style='width:68pt'></td>
  <td width=165 style='width:124pt'></td>
  <td width=79 style='width:59pt'></td>
  <td width=90 style='width:68pt'></td>
  <td width=61 style='width:46pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>




