<?php
	$db=new Database();
	$rptdatefrom = $_POST['rptdatefrom'];
	$rptdateto = $_POST['rptdateto'];
	$statusstnk = $_POST['statusstnk'];
	//error_reporting(0);
	$rptstnk = new Rptstnk();
	$core=new Core();
	$data = $rptstnk->show($rptdatefrom, $rptdateto, $statusstnk);
	extract($data);
?>


<style type="text/css">
    table { page-break-inside:auto }
    tr    { page-break-inside:avoid; page-break-after:auto }
    thead { display:table-header-group }
    tfoot { display:table-footer-group }
	
<!--	@media print {
  <!-- thead {display: table-header-group;}
<!-- }
</style>

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link rel=File-List href="STNK_files/filelist.xml">
<style id="STNK_13321_Styles">
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
.xl6313321
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:18.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6413321
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6513321
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6613321
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	background:#BFBFBF;
	mso-pattern:black none;
	white-space:nowrap;}
.xl6713321
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:9.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6813321
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:9.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:bottom;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
-->
</style>
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="STNK_13321" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=1382 class=xl6413321
 style='border-collapse:collapse;table-layout:fixed;width:1038pt'>
 <col class=xl6413321 width=96 style='mso-width-source:userset;mso-width-alt:
 3510;width:72pt'>
 <col class=xl6413321 width=164 style='mso-width-source:userset;mso-width-alt:
 5997;width:123pt'>
 <col class=xl6413321 width=490 style='mso-width-source:userset;mso-width-alt:
 17920;width:368pt'>
 <col class=xl6413321 width=227 style='mso-width-source:userset;mso-width-alt:
 8301;width:170pt'>
 <col class=xl6413321 width=141 style='mso-width-source:userset;mso-width-alt:
 5156;width:106pt'>
 <col class=xl6413321 width=142 style='mso-width-source:userset;mso-width-alt:
 5193;width:107pt'>
 <col class=xl6413321 width=122 style='mso-width-source:userset;mso-width-alt:
 4461;width:92pt'>
 <tr height=31 style='mso-height-source:userset;height:23.25pt'>
  <td colspan=3 height=31 class=xl6313321 width=750 style='height:23.25pt;
  width:563pt'>MITRA UTAMA MOTOR</td>
  <td class=xl6413321 width=227 style='width:170pt'></td>
  <td class=xl6413321 width=141 style='width:106pt'></td>
  <td class=xl6413321 width=142 style='width:107pt'></td>
  <td class=xl6413321 width=122 style='width:92pt'></td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td colspan=6 height=20 class=xl6513321 width=1260 style='height:15.0pt;
  width:946pt'>LAPORAN STNK KENDARAAN <?php echo $statusstnk; ?></td>
  <td class=xl6413321 width=122 style='width:92pt'></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td colspan=6 height=20 class=xl6513321 width=1260 style='height:15.0pt;
  width:946pt'>PERIODE :  <?php echo $rptdatefrom; ?> SAMPAI <?php echo $rptdateto; ?></td>
  <td class=xl6413321 width=122 style='width:92pt'></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl6613321 style='height:15.0pt'>TANGGAL</td>
  <td class=xl6613321 style='border-left:none'>NAMA</td>
  <td class=xl6613321 style='border-left:none'>ALAMAT</td>
  <td class=xl6613321 style='border-left:none'>TYPE</td>
  <td class=xl6613321 style='border-left:none'>WARNA</td>
  <td class=xl6613321 style='border-left:none'>NO MESIN</td>
  <td class=xl6613321 style='border-left:none'>SALES</td>
 </tr>
 <?php
		$i=1;
		if($data !=0){
		foreach ($data as $value) {
		extract($value);
	?>
 <tr class=xl6513321 height=20 style='height:15.0pt'>
  <td height=20 class=xl6813321 style='height:15.0pt;border-top:none'><?php echo $datetrans; ?></td>
  <td class=xl6713321 style='border-top:none;border-left:none'><?php echo $cusname; ?></td>
  <td class=xl6713321 style='border-top:none;border-left:none'><?php echo $address; ?></td>
  <td class=xl6713321 style='border-top:none;border-left:none'><?php echo $vehicletype; ?></td>
  <td class=xl6713321 style='border-top:none;border-left:none'><?php echo $vehiclecolorname; ?></td>
  <td class=xl6713321 style='border-top:none;border-left:none'><?php echo $mechineno; ?></td>
  <td class=xl6713321 style='border-top:none;border-left:none'><?php echo $employeename; ?></td>
 </tr>
 <?php
	$i++;
		}
		} 
    ?>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=96 style='width:72pt'></td>
  <td width=164 style='width:123pt'></td>
  <td width=490 style='width:368pt'></td>
  <td width=227 style='width:170pt'></td>
  <td width=141 style='width:106pt'></td>
  <td width=142 style='width:107pt'></td>
  <td width=122 style='width:92pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>


